---
apiVersion: v1
kind: Namespace
metadata:
  name: "react-frontend"
---

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: react-frontend
  name: react-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: react-app-service
              port:
                number: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-app"
  namespace: "react-frontend"
spec:
  selector:
    matchLabels:
      app: "react-app"
  replicas: 2
  template:
    metadata:
      labels:
        app: "react-app"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "react-app"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - image: 260757724159.dkr.ecr.us-east-1.amazonaws.com/react_frontend:latest
        imagePullPolicy: Always
        name: "react-app"
        ports:
        - containerPort: 8080
---

---
apiVersion: v1
kind: Service
metadata:
  name: "react-app-service"
  namespace: "react-frontend"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: "react-app"
---